name: CI
on:
  push: { branches: [main] }
  pull_request:

jobs:
  lint-manifests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install kubeconform
        run: |
          curl -sSL https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz | tar xz
          sudo mv kubeconform /usr/local/bin/
      - name: Validate manifests
        run: |
          find . -name '*.yaml' -not -path './.git/*' -not -path './apps/sample-fastapi/chart/*' \
            | xargs kubeconform -strict -ignore-missing-schemas -summary

  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - run: helm lint apps/sample-fastapi/chart

  build-and-scan:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: apps/sample-fastapi
          push: false
          tags: sample-fastapi:ci
          load: true
      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: sample-fastapi:ci
          severity: HIGH,CRITICAL
          exit-code: '0'
